spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.adobe.hackathon: DEBUG

app:
  file:
    storage:
      upload-dir: ./test-uploads
      max-size: 10485760