spring:
  application:
    name: adobe-challenge-1b
  datasource:
    url: jdbc:h2:file:./data/hackathon
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # Enable SQL logging for development
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  autoconfigure:
    exclude: []

server:
  port: 8080
  address: localhost  # Bind to localhost for development
  servlet:
    context-path: /
  compression:
    enabled: false  # Disable compression for development
  http2:
    enabled: false  # Disable HTTP/2 for development

app:
  file:
    storage:
      upload-dir: ./uploads
      max-size: 104857600 # 100MB
  analysis:
    enhanced:
      enabled: true
      max-sections-per-document: 5
      confidence-threshold: 0.7
      detailed-analysis: true
  pdf:
    processing:
      timeout: 300000
    max-pages: 500
  tts:
    enabled: true
    default-duration: 180
    audio-format: mp3
    quality: high
  insights:
    enabled: true
    llm-powered: true
    confidence-threshold: 0.8
  accuracy:
    validation:
      enabled: true
      minimum-threshold: 0.80
      minimum-sections: 3
      cache-enabled: true
  performance:
    monitoring:
      enabled: true
      navigation-threshold: 2000
      analysis-threshold: 10000
      tts-threshold: 30000

cors:
  allowed-origins: "http://localhost:3000,http://127.0.0.1:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

llm:
  provider: gemini
  model: gemini-2.5-flash
  api:
    timeout: 30000
    max-retries: 3
    fallback-enabled: true

tts:
  provider: azure
  api:
    timeout: 60000
    audio-quality: high
    voice: en-US-JennyNeural
    format: mp3

adobe:
  pdf:
    client-id: "demo-client-id"
    client-secret: "demo-client-secret"
    embed-api:
      enabled: true
      fidelity: 100
      zoom-pan-support: true
      responsive-design: true

logging:
  level:
    com.adobe.hackathon: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
    com.adobe.hackathon.service: DEBUG
